"""
Curated, process-specific flowchart step templates.

Used to generate non-generic Mermaid diagrams for processes so that newly
generated processes are not identical templates.
"""

from __future__ import annotations

from typing import Dict, List, Literal, TypedDict

Role = Literal["red", "yellow", "green", "blue", "violet"]


class Step(TypedDict):
    label: str
    role: Role


# Computer science templates (covers the 50-process CS set currently in GCS).
CS_TEMPLATES: Dict[str, List[Step]] = {
    "algorithms_data_structures-balanced-search-trees": [
        {"label": "Keys + Comparison Function", "role": "red"},
        {"label": "Insert/Delete/Search Request", "role": "red"},
        {"label": "Balanced BST Invariant", "role": "yellow"},
        {"label": "Tree Node Structure", "role": "yellow"},
        {"label": "Traverse to Target Position", "role": "green"},
        {"label": "Apply Update (insert/delete)", "role": "green"},
        {"label": "Update Heights/Colors", "role": "blue"},
        {"label": "Detect Imbalance Case", "role": "green"},
        {"label": "Rotation/Recoloring", "role": "green"},
        {"label": "Restore Invariant", "role": "blue"},
        {"label": "Return Updated Root", "role": "violet"},
    ],
    "algorithms_data_structures-dynamic-programming": [
        {"label": "Problem Statement + Constraints", "role": "red"},
        {"label": "Objective Function", "role": "red"},
        {"label": "State Definition", "role": "yellow"},
        {"label": "Recurrence Relation", "role": "yellow"},
        {"label": "Base Cases", "role": "green"},
        {"label": "Choose Top-Down vs Bottom-Up", "role": "green"},
        {"label": "DP Table / Memo Cache", "role": "yellow"},
        {"label": "Compute Subproblems", "role": "green"},
        {"label": "Store Intermediate Values", "role": "blue"},
        {"label": "Reconstruct Solution (optional)", "role": "green"},
        {"label": "Optimal Value + Solution", "role": "violet"},
    ],
    "algorithms_data_structures-graph-algorithms": [
        {"label": "Graph (V,E)", "role": "red"},
        {"label": "Query Type", "role": "red"},
        {"label": "Adjacency Representation", "role": "yellow"},
        {"label": "Weights/Capacities (optional)", "role": "yellow"},
        {"label": "Select Algorithm Family", "role": "green"},
        {"label": "Initialize Structures", "role": "green"},
        {"label": "Iterate Expand/Relax", "role": "green"},
        {"label": "Maintain Invariants", "role": "blue"},
        {"label": "Terminate + Extract Result", "role": "violet"},
    ],
    "algorithms_data_structures-graph-traversal": [
        {"label": "Graph (V,E)", "role": "red"},
        {"label": "Start Node(s)", "role": "red"},
        {"label": "Visited Set", "role": "yellow"},
        {"label": "Frontier (Stack/Queue)", "role": "yellow"},
        {"label": "Pop Next Node", "role": "green"},
        {"label": "Mark Visited", "role": "green"},
        {"label": "Process Node", "role": "green"},
        {"label": "Push Unvisited Neighbors", "role": "green"},
        {"label": "Traversal Order/Tree", "role": "blue"},
        {"label": "Traversal Output", "role": "violet"},
    ],
    "algorithms_data_structures-hash-table-operations": [
        {"label": "Key + Hash Function", "role": "red"},
        {"label": "Operation (get/put/delete)", "role": "red"},
        {"label": "Bucket Array", "role": "yellow"},
        {"label": "Collision Strategy", "role": "yellow"},
        {"label": "Compute Hash/Index", "role": "green"},
        {"label": "Probe/Chain Walk", "role": "green"},
        {"label": "Update Entry", "role": "green"},
        {"label": "Resize/Rehash (if needed)", "role": "blue"},
        {"label": "Return Value/Status", "role": "violet"},
    ],
    "algorithms_data_structures-minimum-spanning-tree": [
        {"label": "Weighted Graph", "role": "red"},
        {"label": "Edge Weights", "role": "red"},
        {"label": "Candidate Edges", "role": "yellow"},
        {"label": "DSU / PQ", "role": "yellow"},
        {"label": "Select Next Safe Edge", "role": "green"},
        {"label": "Cycle Check", "role": "green"},
        {"label": "Add Edge to Tree", "role": "green"},
        {"label": "MST Edge Set", "role": "blue"},
        {"label": "MST Total Weight", "role": "violet"},
    ],
    "algorithms_data_structures-shortest-path-algorithms": [
        {"label": "Graph + Weights", "role": "red"},
        {"label": "Source/Target", "role": "red"},
        {"label": "Distance Array", "role": "yellow"},
        {"label": "Priority Queue", "role": "yellow"},
        {"label": "Initialize dist[source]=0", "role": "green"},
        {"label": "Extract-Min Node", "role": "green"},
        {"label": "Relax Outgoing Edges", "role": "green"},
        {"label": "Update Dist/Parents", "role": "blue"},
        {"label": "Reconstruct Path", "role": "green"},
        {"label": "Shortest Path + Cost", "role": "violet"},
    ],
    "algorithms_data_structures-sorting-algorithms": [
        {"label": "Unsorted Collection", "role": "red"},
        {"label": "Comparator/Key", "role": "red"},
        {"label": "Choose Sort Strategy", "role": "yellow"},
        {"label": "Partition/Merge Structure", "role": "yellow"},
        {"label": "Reorder Elements", "role": "green"},
        {"label": "Maintain Order Invariant", "role": "blue"},
        {"label": "Sorted Output", "role": "violet"},
    ],

    "machine_learning-feature-engineering-pipeline": [
        {"label": "Raw Data", "role": "red"},
        {"label": "Target Definition", "role": "red"},
        {"label": "Schema + Types", "role": "yellow"},
        {"label": "Train/Val Split", "role": "yellow"},
        {"label": "Clean/Impute", "role": "green"},
        {"label": "Encode/Scale", "role": "green"},
        {"label": "Generate Features", "role": "green"},
        {"label": "Select Features", "role": "green"},
        {"label": "Feature Dataset Artifact", "role": "blue"},
        {"label": "Model-Ready Features", "role": "violet"},
    ],
    "machine_learning-hyperparameter-optimization": [
        {"label": "Model Family", "role": "red"},
        {"label": "Metric + Budget", "role": "red"},
        {"label": "Search Space", "role": "yellow"},
        {"label": "Sampler Strategy", "role": "yellow"},
        {"label": "Propose Params", "role": "green"},
        {"label": "Train Candidate", "role": "green"},
        {"label": "Validate Candidate", "role": "green"},
        {"label": "Trial History", "role": "blue"},
        {"label": "Best Parameters", "role": "violet"},
    ],
    "machine_learning-model-evaluation-and-validation": [
        {"label": "Trained Model", "role": "red"},
        {"label": "Holdout/Test Data", "role": "red"},
        {"label": "Evaluation Protocol", "role": "yellow"},
        {"label": "Metrics", "role": "yellow"},
        {"label": "Run Predictions", "role": "green"},
        {"label": "Compute Metrics", "role": "green"},
        {"label": "Error Analysis", "role": "blue"},
        {"label": "Validation Report", "role": "violet"},
    ],
    "machine_learning-model-training-pipeline": [
        {"label": "Training Data", "role": "red"},
        {"label": "Loss Function", "role": "red"},
        {"label": "Model Architecture", "role": "yellow"},
        {"label": "Optimizer Config", "role": "yellow"},
        {"label": "Forward Pass", "role": "green"},
        {"label": "Backpropagation", "role": "green"},
        {"label": "Optimizer Step", "role": "green"},
        {"label": "Checkpoint State", "role": "blue"},
        {"label": "Trained Model", "role": "violet"},
    ],
    "machine_learning-project-management": [
        {"label": "Project Charter", "role": "red"},
        {"label": "Goals + Stakeholders", "role": "red"},
        {"label": "Scope/Backlog", "role": "yellow"},
        {"label": "Team + Roles", "role": "yellow"},
        {"label": "Plan Milestones", "role": "green"},
        {"label": "Execute Work", "role": "green"},
        {"label": "Track Progress", "role": "blue"},
        {"label": "Mitigate Risks", "role": "green"},
        {"label": "Deliver Outcome", "role": "violet"},
    ],
    "machine_learning-quality-assurance": [
        {"label": "Requirements", "role": "red"},
        {"label": "Acceptance Criteria", "role": "red"},
        {"label": "Test Plan", "role": "yellow"},
        {"label": "Test Data", "role": "yellow"},
        {"label": "Run Automated Tests", "role": "green"},
        {"label": "Run Manual QA", "role": "green"},
        {"label": "Defect Triage", "role": "blue"},
        {"label": "Release Decision", "role": "violet"},
    ],
    "machine_learning-software-development-lifecycle": [
        {"label": "Requirements", "role": "red"},
        {"label": "Constraints", "role": "red"},
        {"label": "Architecture", "role": "yellow"},
        {"label": "Implementation Plan", "role": "yellow"},
        {"label": "Develop", "role": "green"},
        {"label": "Test", "role": "green"},
        {"label": "Deploy", "role": "green"},
        {"label": "Monitor", "role": "blue"},
        {"label": "Maintain", "role": "violet"},
    ],

    "networks-dns-resolution": [
        {"label": "Client Query", "role": "red"},
        {"label": "Domain Name", "role": "red"},
        {"label": "Resolver Cache", "role": "yellow"},
        {"label": "Recursive Resolver", "role": "yellow"},
        {"label": "Check Cache", "role": "green"},
        {"label": "Query Root/TLD/Auth", "role": "green"},
        {"label": "DNS Response", "role": "blue"},
        {"label": "Return IP Address", "role": "violet"},
    ],
    "networks-database-design": [
        {"label": "Requirements", "role": "red"},
        {"label": "Data Domains", "role": "red"},
        {"label": "Entities/Attributes", "role": "yellow"},
        {"label": "Constraints", "role": "yellow"},
        {"label": "Normalize Schema", "role": "green"},
        {"label": "Index Strategy", "role": "green"},
        {"label": "Migration Plan", "role": "blue"},
        {"label": "Deployed Schema", "role": "violet"},
    ],
    "networks-load-balancing": [
        {"label": "Incoming Requests", "role": "red"},
        {"label": "Traffic Pattern", "role": "red"},
        {"label": "Load Balancer", "role": "yellow"},
        {"label": "Backend Pool", "role": "yellow"},
        {"label": "Health Checks", "role": "green"},
        {"label": "Choose Backend", "role": "green"},
        {"label": "Route Request", "role": "green"},
        {"label": "Observed Latency/Errors", "role": "blue"},
        {"label": "Balanced Service", "role": "violet"},
    ],
    "networks-query-processing": [
        {"label": "SQL Query", "role": "red"},
        {"label": "Parameters", "role": "red"},
        {"label": "Parser/Planner", "role": "yellow"},
        {"label": "Stats + Indexes", "role": "yellow"},
        {"label": "Optimize Plan", "role": "green"},
        {"label": "Execute Operators", "role": "green"},
        {"label": "Intermediate Results", "role": "blue"},
        {"label": "Result Set", "role": "violet"},
    ],
    "networks-routing-protocol-operation": [
        {"label": "Network Topology", "role": "red"},
        {"label": "Link Updates", "role": "red"},
        {"label": "Neighbors", "role": "yellow"},
        {"label": "Routing Table", "role": "yellow"},
        {"label": "Exchange Updates", "role": "green"},
        {"label": "Compute Best Paths", "role": "green"},
        {"label": "Converged Routes", "role": "blue"},
        {"label": "Forwarding Decisions", "role": "violet"},
    ],
    "networks-tcp-congestion-control": [
        {"label": "TCP Connection", "role": "red"},
        {"label": "ACK/Loss Signals", "role": "red"},
        {"label": "cwnd + ssthresh", "role": "yellow"},
        {"label": "RTT Estimator", "role": "yellow"},
        {"label": "Slow Start", "role": "green"},
        {"label": "Congestion Avoidance", "role": "green"},
        {"label": "Fast Recovery", "role": "green"},
        {"label": "Stable Throughput", "role": "blue"},
        {"label": "Adaptive Send Rate", "role": "violet"},
    ],
    "networks-transaction-management": [
        {"label": "Transaction Request", "role": "red"},
        {"label": "Read/Write Set", "role": "red"},
        {"label": "Locking/MVCC", "role": "yellow"},
        {"label": "Write-Ahead Log", "role": "yellow"},
        {"label": "Execute Statements", "role": "green"},
        {"label": "Commit/Abort", "role": "green"},
        {"label": "Durable State", "role": "blue"},
        {"label": "Committed Result", "role": "violet"},
    ],

    "security-authentication-and-authorization": [
        {"label": "User Request", "role": "red"},
        {"label": "Credentials/Token", "role": "red"},
        {"label": "Identity Provider", "role": "yellow"},
        {"label": "Policy/Role Store", "role": "yellow"},
        {"label": "Authenticate Identity", "role": "green"},
        {"label": "Authorize Action", "role": "green"},
        {"label": "Decision", "role": "violet"},
    ],
    "security-file-system": [
        {"label": "Filesystem Request", "role": "red"},
        {"label": "Path + Operation", "role": "red"},
        {"label": "Inodes/Metadata", "role": "yellow"},
        {"label": "Block Device", "role": "yellow"},
        {"label": "Lookup + Permission Check", "role": "green"},
        {"label": "Read/Write Blocks", "role": "green"},
        {"label": "Cache State", "role": "blue"},
        {"label": "I/O Result", "role": "violet"},
    ],
    "security-intrusion-detection": [
        {"label": "Telemetry Streams", "role": "red"},
        {"label": "Threat Model", "role": "red"},
        {"label": "Sensors/Agents", "role": "yellow"},
        {"label": "Rules/ML Model", "role": "yellow"},
        {"label": "Normalize Events", "role": "green"},
        {"label": "Detect + Alert", "role": "green"},
        {"label": "Incident Ticket", "role": "violet"},
    ],
    "security-memory-management": [
        {"label": "Allocation Request", "role": "red"},
        {"label": "Address Space", "role": "red"},
        {"label": "Page Tables", "role": "yellow"},
        {"label": "Allocator Structures", "role": "yellow"},
        {"label": "Map Pages", "role": "green"},
        {"label": "Enforce Protections", "role": "green"},
        {"label": "Working Set", "role": "blue"},
        {"label": "Mapped Memory", "role": "violet"},
    ],
    "security-process-management": [
        {"label": "Process Creation", "role": "red"},
        {"label": "Program Image", "role": "red"},
        {"label": "PCB + Queues", "role": "yellow"},
        {"label": "Scheduler Policy", "role": "yellow"},
        {"label": "Fork/Exec", "role": "green"},
        {"label": "Context Switch", "role": "green"},
        {"label": "Process State", "role": "blue"},
        {"label": "Running Process", "role": "violet"},
    ],
    "security-public-key-infrastructure-pki": [
        {"label": "Identity Claim", "role": "red"},
        {"label": "Key Pair", "role": "red"},
        {"label": "Certificate Authority", "role": "yellow"},
        {"label": "Certificate Store", "role": "yellow"},
        {"label": "Create CSR", "role": "green"},
        {"label": "Issue/Validate Cert", "role": "green"},
        {"label": "Trusted Identity", "role": "violet"},
    ],
    "security-secure-software-update": [
        {"label": "Update Available", "role": "red"},
        {"label": "Device State", "role": "red"},
        {"label": "Manifest", "role": "yellow"},
        {"label": "Signature/Keys", "role": "yellow"},
        {"label": "Download Payload", "role": "green"},
        {"label": "Verify Signature", "role": "green"},
        {"label": "Install Atomically", "role": "green"},
        {"label": "Updated System", "role": "violet"},
    ],

    "software_engineering-code-review-workflow": [
        {"label": "Pull Request", "role": "red"},
        {"label": "Change Context", "role": "red"},
        {"label": "Reviewers", "role": "yellow"},
        {"label": "Diff + Checks", "role": "yellow"},
        {"label": "Automated CI", "role": "green"},
        {"label": "Human Review", "role": "green"},
        {"label": "Address Feedback", "role": "green"},
        {"label": "Merge", "role": "violet"},
    ],
    "software_engineering-continuous-integration-pipeline": [
        {"label": "Commit/PR Event", "role": "red"},
        {"label": "Pipeline Config", "role": "red"},
        {"label": "Runner", "role": "yellow"},
        {"label": "Artifacts", "role": "yellow"},
        {"label": "Build", "role": "green"},
        {"label": "Test", "role": "green"},
        {"label": "Report Status", "role": "blue"},
        {"label": "Green Build", "role": "violet"},
    ],
    "software_engineering-incident-response": [
        {"label": "Alert Trigger", "role": "red"},
        {"label": "Service Impact", "role": "red"},
        {"label": "On-Call Team", "role": "yellow"},
        {"label": "Runbooks", "role": "yellow"},
        {"label": "Triage", "role": "green"},
        {"label": "Mitigate", "role": "green"},
        {"label": "Postmortem", "role": "blue"},
        {"label": "Resolved Incident", "role": "violet"},
    ],
    "software_engineering-machine-learning": [
        {"label": "Data + Labels", "role": "red"},
        {"label": "Objective Metric", "role": "red"},
        {"label": "Feature Pipeline", "role": "yellow"},
        {"label": "Model Family", "role": "yellow"},
        {"label": "Train", "role": "green"},
        {"label": "Validate", "role": "green"},
        {"label": "Deploy", "role": "green"},
        {"label": "Monitor", "role": "blue"},
        {"label": "Production Model", "role": "violet"},
    ],
    "software_engineering-natural-language-processing": [
        {"label": "Text Corpus", "role": "red"},
        {"label": "Task Definition", "role": "red"},
        {"label": "Tokenizer", "role": "yellow"},
        {"label": "Model", "role": "yellow"},
        {"label": "Preprocess", "role": "green"},
        {"label": "Train/Fine-tune", "role": "green"},
        {"label": "Evaluate", "role": "blue"},
        {"label": "NLP Output", "role": "violet"},
    ],
    "software_engineering-neural-network": [
        {"label": "Training Data", "role": "red"},
        {"label": "Loss + Metric", "role": "red"},
        {"label": "Layers", "role": "yellow"},
        {"label": "Optimizer", "role": "yellow"},
        {"label": "Forward", "role": "green"},
        {"label": "Backprop", "role": "green"},
        {"label": "Updated Weights", "role": "blue"},
        {"label": "Trained Network", "role": "violet"},
    ],
    "software_engineering-requirements-engineering": [
        {"label": "Stakeholder Needs", "role": "red"},
        {"label": "Business Goals", "role": "red"},
        {"label": "Backlog", "role": "yellow"},
        {"label": "Constraints", "role": "yellow"},
        {"label": "Elicit + Document", "role": "green"},
        {"label": "Validate + Prioritize", "role": "green"},
        {"label": "Approved Requirements", "role": "violet"},
    ],

    "systems-container-orchestration": [
        {"label": "Desired Services", "role": "red"},
        {"label": "Cluster Resources", "role": "red"},
        {"label": "Control Plane", "role": "yellow"},
        {"label": "Scheduler", "role": "yellow"},
        {"label": "Deploy Workloads", "role": "green"},
        {"label": "Service Discovery", "role": "green"},
        {"label": "Auto-Scale", "role": "green"},
        {"label": "Observed State", "role": "blue"},
        {"label": "Running Cluster", "role": "violet"},
    ],
    "systems-file-system-journaling": [
        {"label": "Write Operation", "role": "red"},
        {"label": "Crash Risk", "role": "red"},
        {"label": "Journal", "role": "yellow"},
        {"label": "Metadata Blocks", "role": "yellow"},
        {"label": "Log Intent", "role": "green"},
        {"label": "Apply Updates", "role": "green"},
        {"label": "Recovery Replay", "role": "blue"},
        {"label": "Consistent FS", "role": "violet"},
    ],
    "systems-network-performance": [
        {"label": "Traffic Load", "role": "red"},
        {"label": "SLO Targets", "role": "red"},
        {"label": "Instrumentation", "role": "yellow"},
        {"label": "Bottlenecks", "role": "yellow"},
        {"label": "Measure", "role": "green"},
        {"label": "Optimize", "role": "green"},
        {"label": "New Baseline", "role": "blue"},
        {"label": "Improved Performance", "role": "violet"},
    ],
    "systems-network-protocol": [
        {"label": "Endpoints", "role": "red"},
        {"label": "Payload", "role": "red"},
        {"label": "Protocol Spec", "role": "yellow"},
        {"label": "State Machine", "role": "yellow"},
        {"label": "Handshake", "role": "green"},
        {"label": "Transmit", "role": "green"},
        {"label": "Session State", "role": "blue"},
        {"label": "Delivered Data", "role": "violet"},
    ],
    "systems-network-security": [
        {"label": "Network Traffic", "role": "red"},
        {"label": "Threats", "role": "red"},
        {"label": "Policies", "role": "yellow"},
        {"label": "Keys", "role": "yellow"},
        {"label": "Encrypt/Inspect", "role": "green"},
        {"label": "Block/Alert", "role": "green"},
        {"label": "Protected Network", "role": "violet"},
    ],
    "systems-process-scheduling": [
        {"label": "Runnable Processes", "role": "red"},
        {"label": "CPU Availability", "role": "red"},
        {"label": "Policy", "role": "yellow"},
        {"label": "Run Queue", "role": "yellow"},
        {"label": "Select Next", "role": "green"},
        {"label": "Context Switch", "role": "green"},
        {"label": "Process States", "role": "blue"},
        {"label": "Fair Scheduling", "role": "violet"},
    ],
    "systems-virtual-memory-paging": [
        {"label": "Virtual Address", "role": "red"},
        {"label": "Access Request", "role": "red"},
        {"label": "Page Table", "role": "yellow"},
        {"label": "Physical Frames", "role": "yellow"},
        {"label": "Translate", "role": "green"},
        {"label": "Handle Page Fault", "role": "green"},
        {"label": "Working Set", "role": "blue"},
        {"label": "Mapped Address", "role": "violet"},
    ],

    "theory-animation": [
        {"label": "Scene Inputs", "role": "red"},
        {"label": "Keyframes", "role": "red"},
        {"label": "Rig/Transforms", "role": "yellow"},
        {"label": "Interpolation", "role": "green"},
        {"label": "Render Frames", "role": "green"},
        {"label": "Frame Buffer", "role": "blue"},
        {"label": "Animated Output", "role": "violet"},
    ],
    "theory-automata-construction": [
        {"label": "Language Spec", "role": "red"},
        {"label": "Alphabet Σ", "role": "red"},
        {"label": "States Q", "role": "yellow"},
        {"label": "Transitions δ", "role": "yellow"},
        {"label": "Build Automaton", "role": "green"},
        {"label": "Minimize/Determinize", "role": "green"},
        {"label": "Recognizer", "role": "violet"},
    ],
    "theory-computational-complexity-analysis": [
        {"label": "Algorithm", "role": "red"},
        {"label": "Input Size n", "role": "red"},
        {"label": "Cost Model", "role": "yellow"},
        {"label": "Dominant Ops", "role": "yellow"},
        {"label": "Count Steps", "role": "green"},
        {"label": "Solve Asymptotics", "role": "green"},
        {"label": "Big-O Bound", "role": "violet"},
    ],
    "theory-formal-verification": [
        {"label": "Specification", "role": "red"},
        {"label": "Properties", "role": "red"},
        {"label": "Formal Model", "role": "yellow"},
        {"label": "Proof Artifacts", "role": "yellow"},
        {"label": "Model Check/Prove", "role": "green"},
        {"label": "Counterexamples", "role": "blue"},
        {"label": "Verified Properties", "role": "violet"},
    ],
    "theory-geometric-modeling": [
        {"label": "Geometry Inputs", "role": "red"},
        {"label": "Constraints", "role": "red"},
        {"label": "Mesh/NURBS", "role": "yellow"},
        {"label": "Topology", "role": "yellow"},
        {"label": "Construct/Refine", "role": "green"},
        {"label": "Model State", "role": "blue"},
        {"label": "Geometric Model", "role": "violet"},
    ],
    "theory-rendering": [
        {"label": "Scene + Camera", "role": "red"},
        {"label": "Lights + Materials", "role": "red"},
        {"label": "Geometry Buffers", "role": "yellow"},
        {"label": "Shaders", "role": "yellow"},
        {"label": "Rasterize/Shade", "role": "green"},
        {"label": "Post-Process", "role": "green"},
        {"label": "Frame Buffer", "role": "blue"},
        {"label": "Rendered Image", "role": "violet"},
    ],
    "theory-type-system-checking": [
        {"label": "Source Program", "role": "red"},
        {"label": "Type Annotations", "role": "red"},
        {"label": "AST", "role": "yellow"},
        {"label": "Type Environment", "role": "yellow"},
        {"label": "Infer + Unify", "role": "green"},
        {"label": "Type Errors/Proof", "role": "blue"},
        {"label": "Well-Typed Program", "role": "violet"},
    ],
}


# Chemistry templates for the newly-added expansion set (optional; fill in as needed).
CHEMISTRY_TEMPLATES: Dict[str, List[Step]] = {
    "organic_chemistry-aldol-condensation": [
        {"label": "Carbonyl Substrates", "role": "red"},
        {"label": "Base/Acid Conditions", "role": "red"},
        {"label": "Enolate/Enol Formation", "role": "green"},
        {"label": "C–C Bond Formation (Addition)", "role": "green"},
        {"label": "β-Hydroxy Carbonyl (Aldol)", "role": "blue"},
        {"label": "Dehydration", "role": "green"},
        {"label": "α,β-Unsaturated Carbonyl", "role": "violet"},
    ],
    "organic_chemistry-grignard-reaction": [
        {"label": "Alkyl Halide + Mg", "role": "red"},
        {"label": "Dry Ether Solvent", "role": "red"},
        {"label": "Grignard Reagent (RMgX)", "role": "blue"},
        {"label": "Carbonyl Electrophile", "role": "yellow"},
        {"label": "Nucleophilic Addition", "role": "green"},
        {"label": "Alkoxide Intermediate", "role": "blue"},
        {"label": "Acid Workup", "role": "green"},
        {"label": "Alcohol Product", "role": "violet"},
    ],
    "organic_chemistry-suzuki-coupling": [
        {"label": "Aryl/Vinyl Halide", "role": "red"},
        {"label": "Boronic Acid/Ester", "role": "red"},
        {"label": "Pd Catalyst + Base", "role": "yellow"},
        {"label": "Oxidative Addition", "role": "green"},
        {"label": "Transmetalation", "role": "green"},
        {"label": "Reductive Elimination", "role": "green"},
        {"label": "Biaryl Product", "role": "violet"},
    ],
    "organic_chemistry-esterification": [
        {"label": "Carboxylic Acid", "role": "red"},
        {"label": "Alcohol", "role": "red"},
        {"label": "Acid Catalyst", "role": "yellow"},
        {"label": "Tetrahedral Intermediate", "role": "blue"},
        {"label": "Water Elimination", "role": "green"},
        {"label": "Ester Product", "role": "violet"},
    ],
    "physical_chemistry-phase-diagram-construction": [
        {"label": "System + Components", "role": "red"},
        {"label": "T/P Range", "role": "red"},
        {"label": "Equilibrium Measurements", "role": "yellow"},
        {"label": "Identify Phase Regions", "role": "green"},
        {"label": "Locate Phase Boundaries", "role": "green"},
        {"label": "Critical/Triple Points", "role": "blue"},
        {"label": "Phase Diagram", "role": "violet"},
    ],
    "physical_chemistry-reaction-rate-measurement": [
        {"label": "Reactants + Conditions", "role": "red"},
        {"label": "Analytical Readout", "role": "red"},
        {"label": "Concentration vs Time", "role": "blue"},
        {"label": "Initial Rate/Integrated Law", "role": "yellow"},
        {"label": "Fit Rate Parameters", "role": "green"},
        {"label": "Rate Constant k", "role": "violet"},
    ],
    "physical_chemistry-spectroscopic-line-broadening": [
        {"label": "Spectral Data", "role": "red"},
        {"label": "Instrument Settings", "role": "red"},
        {"label": "Broadening Mechanisms", "role": "yellow"},
        {"label": "Line-Shape Model", "role": "yellow"},
        {"label": "Fit Line Profile", "role": "green"},
        {"label": "Width Parameters", "role": "violet"},
    ],
    "analytical_chemistry-calibration-curve-construction": [
        {"label": "Calibration Standards", "role": "red"},
        {"label": "Instrument Response", "role": "red"},
        {"label": "Regression Model", "role": "yellow"},
        {"label": "Fit + Residual Check", "role": "green"},
        {"label": "LOD/LOQ Estimate", "role": "blue"},
        {"label": "Calibration Function", "role": "violet"},
    ],
    "analytical_chemistry-sample-preparation-workflow": [
        {"label": "Raw Sample", "role": "red"},
        {"label": "Target Analyte", "role": "red"},
        {"label": "Containers/Consumables", "role": "yellow"},
        {"label": "Homogenize", "role": "green"},
        {"label": "Extract/Cleanup", "role": "green"},
        {"label": "Dilute/Derivatize", "role": "green"},
        {"label": "Prepared Sample", "role": "violet"},
    ],
    "analytical_chemistry-quality-control-and-method-validation": [
        {"label": "Candidate Method", "role": "red"},
        {"label": "QC Samples", "role": "red"},
        {"label": "Acceptance Criteria", "role": "yellow"},
        {"label": "Accuracy/Precision", "role": "green"},
        {"label": "Robustness/Linearity", "role": "green"},
        {"label": "Validated Method", "role": "violet"},
    ],
    "inorganic_chemistry-ligand-substitution": [
        {"label": "Metal Complex", "role": "red"},
        {"label": "Incoming Ligand", "role": "red"},
        {"label": "Coordination Sphere", "role": "yellow"},
        {"label": "Mechanism Choice (A/D/I)", "role": "yellow"},
        {"label": "Substitution Step", "role": "green"},
        {"label": "New Complex", "role": "violet"},
    ],
    "inorganic_chemistry-coordination-complex-synthesis": [
        {"label": "Metal Salt", "role": "red"},
        {"label": "Ligands", "role": "red"},
        {"label": "Solvent/Atmosphere", "role": "yellow"},
        {"label": "Complexation Reaction", "role": "green"},
        {"label": "Purify/Crystallize", "role": "green"},
        {"label": "Characterized Complex", "role": "violet"},
    ],
    "inorganic_chemistry-metal-oxide-formation": [
        {"label": "Metal Precursor", "role": "red"},
        {"label": "Oxidant/Heat", "role": "red"},
        {"label": "Nucleation Sites", "role": "yellow"},
        {"label": "Growth/Calcination", "role": "green"},
        {"label": "Metal Oxide", "role": "violet"},
    ],
    "materials_chemistry-sol-gel-synthesis": [
        {"label": "Metal Alkoxide", "role": "red"},
        {"label": "Water + Catalyst", "role": "red"},
        {"label": "Hydrolysis", "role": "green"},
        {"label": "Condensation", "role": "green"},
        {"label": "Gel Network", "role": "blue"},
        {"label": "Dry/Calcine", "role": "green"},
        {"label": "Oxide Material", "role": "violet"},
    ],
    "materials_chemistry-thin-film-deposition": [
        {"label": "Substrate", "role": "red"},
        {"label": "Precursor/Target", "role": "red"},
        {"label": "Deposition Tool (CVD/PVD)", "role": "yellow"},
        {"label": "Deposition Parameters", "role": "yellow"},
        {"label": "Film Growth", "role": "green"},
        {"label": "Anneal/Pattern (optional)", "role": "green"},
        {"label": "Thin Film", "role": "violet"},
    ],
    "materials_chemistry-polymerization-process": [
        {"label": "Monomers", "role": "red"},
        {"label": "Initiator/Catalyst", "role": "red"},
        {"label": "Reactor", "role": "yellow"},
        {"label": "Initiation", "role": "green"},
        {"label": "Propagation", "role": "green"},
        {"label": "Termination", "role": "green"},
        {"label": "Polymer Product", "role": "violet"},
    ],
    "environmental_chemistry-water-treatment-coagulation-flocculation": [
        {"label": "Raw Water", "role": "red"},
        {"label": "Coagulant Dose", "role": "red"},
        {"label": "Mixing Basin", "role": "yellow"},
        {"label": "Coagulation", "role": "green"},
        {"label": "Floc Growth", "role": "blue"},
        {"label": "Settling/Filtration", "role": "green"},
        {"label": "Treated Water", "role": "violet"},
    ],
    "environmental_chemistry-atmospheric-aerosol-formation": [
        {"label": "Gas Precursors", "role": "red"},
        {"label": "Oxidants (OH/O3/NO3)", "role": "red"},
        {"label": "Nucleation", "role": "green"},
        {"label": "Condensation/Coagulation", "role": "green"},
        {"label": "Aerosol Particles", "role": "violet"},
    ],
    "environmental_chemistry-soil-contaminant-remediation": [
        {"label": "Contaminated Soil", "role": "red"},
        {"label": "Contaminant Profile", "role": "red"},
        {"label": "Remediation Strategy", "role": "yellow"},
        {"label": "Apply Treatment", "role": "green"},
        {"label": "Monitor Outcomes", "role": "blue"},
        {"label": "Remediated Soil", "role": "violet"},
    ],
    "electrochemistry-cyclic-voltammetry": [
        {"label": "Analyte + Electrolyte", "role": "red"},
        {"label": "Working/Ref/Counter Electrodes", "role": "red"},
        {"label": "Potentiostat", "role": "yellow"},
        {"label": "Potential Sweep", "role": "green"},
        {"label": "Measure Current", "role": "green"},
        {"label": "Voltammogram", "role": "violet"},
    ],
    "electrochemistry-electrodeposition": [
        {"label": "Metal Ion Solution", "role": "red"},
        {"label": "Substrate/Cathode", "role": "red"},
        {"label": "Power Supply", "role": "yellow"},
        {"label": "Apply Potential/Current", "role": "green"},
        {"label": "Nucleation/Growth", "role": "green"},
        {"label": "Deposited Film/Coating", "role": "violet"},
    ],
    "electrochemistry-fuel-cell-operation": [
        {"label": "Fuel + Oxidant", "role": "red"},
        {"label": "Load Demand", "role": "red"},
        {"label": "Electrodes + Membrane", "role": "yellow"},
        {"label": "Anode Oxidation", "role": "green"},
        {"label": "Cathode Reduction", "role": "green"},
        {"label": "Ion Transport", "role": "blue"},
        {"label": "Electrical Power", "role": "violet"},
    ],
    "surface_chemistry-adsorption-isotherm-analysis": [
        {"label": "Adsorbent Material", "role": "red"},
        {"label": "Adsorbate/Pressure", "role": "red"},
        {"label": "Surface Sites", "role": "yellow"},
        {"label": "Measure Uptake", "role": "green"},
        {"label": "Fit Isotherm Model", "role": "green"},
        {"label": "Capacity/Parameters", "role": "violet"},
    ],
    "catalysis-heterogeneous-catalyst-screening": [
        {"label": "Catalyst Candidates", "role": "red"},
        {"label": "Test Reaction + Conditions", "role": "red"},
        {"label": "Reactor/Automation", "role": "yellow"},
        {"label": "Run Screening Experiments", "role": "green"},
        {"label": "Measure Conversion/Selectivity", "role": "green"},
        {"label": "Ranked Catalysts", "role": "violet"},
    ],
    "thermodynamics-gibbs-free-energy-calculation": [
        {"label": "Reaction/Process Definition", "role": "red"},
        {"label": "T,P Conditions", "role": "red"},
        {"label": "ΔH, ΔS Data", "role": "yellow"},
        {"label": "Compute ΔG = ΔH − TΔS", "role": "green"},
        {"label": "Spontaneity/Equilibrium Insight", "role": "violet"},
    ],
    "thermodynamics-chemical-potential-determination": [
        {"label": "System Composition", "role": "red"},
        {"label": "T,P Conditions", "role": "red"},
        {"label": "Equation of State/Model", "role": "yellow"},
        {"label": "Compute μ (chemical potential)", "role": "green"},
        {"label": "μ Values/Activities", "role": "violet"},
    ],
    "kinetics-arrhenius-analysis": [
        {"label": "Rate Constants vs Temperature", "role": "red"},
        {"label": "Temperature Range", "role": "red"},
        {"label": "Arrhenius Model", "role": "yellow"},
        {"label": "Fit ln(k) vs 1/T", "role": "green"},
        {"label": "Ea + A Parameters", "role": "violet"},
    ],
    "kinetics-reaction-mechanism-elucidation": [
        {"label": "Observed Products/Intermediates", "role": "red"},
        {"label": "Kinetic Data", "role": "red"},
        {"label": "Candidate Mechanisms", "role": "yellow"},
        {"label": "Design Probing Experiments", "role": "green"},
        {"label": "Compare Predictions vs Data", "role": "green"},
        {"label": "Supported Mechanism", "role": "violet"},
    ],
    "computational_chemistry-density-functional-theory-workflow": [
        {"label": "Molecular Structure", "role": "red"},
        {"label": "Property Target", "role": "red"},
        {"label": "Functional + Basis Set", "role": "yellow"},
        {"label": "Geometry Optimization", "role": "green"},
        {"label": "Single-Point/Properties", "role": "green"},
        {"label": "Computed Energies/Orbitals", "role": "violet"},
    ],
    "computational_chemistry-molecular-dynamics-simulation-setup": [
        {"label": "Initial Coordinates", "role": "red"},
        {"label": "Simulation Goals", "role": "red"},
        {"label": "Force Field", "role": "yellow"},
        {"label": "Solvation/Box", "role": "yellow"},
        {"label": "Minimize + Equilibrate", "role": "green"},
        {"label": "Production Run", "role": "green"},
        {"label": "Trajectory", "role": "violet"},
    ],
    "spectroscopy-raman-spectroscopy-analysis": [
        {"label": "Sample", "role": "red"},
        {"label": "Laser Settings", "role": "red"},
        {"label": "Spectrometer", "role": "yellow"},
        {"label": "Acquire Spectrum", "role": "green"},
        {"label": "Baseline/Peak Fit", "role": "green"},
        {"label": "Raman Peaks/Assignments", "role": "violet"},
    ],
    "spectroscopy-x-ray-diffraction-analysis": [
        {"label": "Crystalline Sample", "role": "red"},
        {"label": "X-ray Source", "role": "red"},
        {"label": "Diffractometer", "role": "yellow"},
        {"label": "Acquire Pattern", "role": "green"},
        {"label": "Index Peaks/Refine", "role": "green"},
        {"label": "Lattice/Phase Identification", "role": "violet"},
    ],
}


# Chemistry subcategory templates (ensures every chemistry process gets a non-generic chart).
# These are intentionally "canonical workflows" for each subfield; they prevent identical charts
# across unrelated processes even when we don't have a process-specific template yet.
CHEMISTRY_SUBCATEGORY_TEMPLATES: Dict[str, List[Step]] = {
    "analytical_chemistry": [
        {"label": "Sample + Analyte Target", "role": "red"},
        {"label": "Method Selection", "role": "yellow"},
        {"label": "Sample Preparation", "role": "green"},
        {"label": "Calibration + QC", "role": "yellow"},
        {"label": "Instrument Measurement", "role": "green"},
        {"label": "Signal Processing", "role": "green"},
        {"label": "Quantitation + Uncertainty", "role": "blue"},
        {"label": "Reported Concentration/Result", "role": "violet"},
    ],
    "biochemistry": [
        {"label": "Biomolecule/System", "role": "red"},
        {"label": "Assay/Readout Choice", "role": "yellow"},
        {"label": "Prepare Buffers/Reagents", "role": "yellow"},
        {"label": "Run Experiment", "role": "green"},
        {"label": "Kinetic/Structural Data", "role": "blue"},
        {"label": "Interpret Mechanism/Function", "role": "green"},
        {"label": "Biochemical Insight", "role": "violet"},
    ],
    "computational_chemistry": [
        {"label": "Molecular Structure", "role": "red"},
        {"label": "Property/Observable Target", "role": "red"},
        {"label": "Model (force field / QM method)", "role": "yellow"},
        {"label": "Simulation/Calculation Setup", "role": "yellow"},
        {"label": "Run Computation", "role": "green"},
        {"label": "Analyze Energies/Geometries/Spectra", "role": "green"},
        {"label": "Computed Properties", "role": "violet"},
    ],
    "electrochemistry": [
        {"label": "Electrochemical System", "role": "red"},
        {"label": "Electrodes + Electrolyte", "role": "yellow"},
        {"label": "Cell Configuration", "role": "yellow"},
        {"label": "Control Potential/Current", "role": "green"},
        {"label": "Measure Response", "role": "green"},
        {"label": "Kinetics/Transport Interpretation", "role": "blue"},
        {"label": "Electrochemical Outcome", "role": "violet"},
    ],
    "environmental_chemistry": [
        {"label": "Environmental Matrix (air/water/soil)", "role": "red"},
        {"label": "Contaminants/Species of Interest", "role": "red"},
        {"label": "Sampling Strategy", "role": "yellow"},
        {"label": "Transport/Transformation Processes", "role": "yellow"},
        {"label": "Measurement/Modeling", "role": "green"},
        {"label": "Risk/Impact Assessment", "role": "blue"},
        {"label": "Mitigation/Policy Action", "role": "violet"},
    ],
    "inorganic_chemistry": [
        {"label": "Metal Center + Ligands", "role": "red"},
        {"label": "Oxidation State/Coordination Goals", "role": "yellow"},
        {"label": "Reagents + Solvent/Atmosphere", "role": "yellow"},
        {"label": "Synthesis/Complexation", "role": "green"},
        {"label": "Purification/Isolation", "role": "green"},
        {"label": "Characterization (spectra/structure)", "role": "blue"},
        {"label": "Inorganic Compound", "role": "violet"},
    ],
    "kinetics": [
        {"label": "Reaction System", "role": "red"},
        {"label": "Conditions (T, P, concentrations)", "role": "red"},
        {"label": "Measurement Method", "role": "yellow"},
        {"label": "Acquire Rate Data", "role": "green"},
        {"label": "Fit Rate Law/Parameters", "role": "green"},
        {"label": "Mechanistic Inference", "role": "blue"},
        {"label": "Kinetic Model", "role": "violet"},
    ],
    "materials_chemistry": [
        {"label": "Target Material + Specs", "role": "red"},
        {"label": "Precursors", "role": "red"},
        {"label": "Synthesis Route", "role": "yellow"},
        {"label": "Process (synthesis/deposition)", "role": "green"},
        {"label": "Microstructure Formation", "role": "blue"},
        {"label": "Characterization", "role": "green"},
        {"label": "Material Product", "role": "violet"},
    ],
    "materials_science": [
        {"label": "Material System", "role": "red"},
        {"label": "Property Target", "role": "red"},
        {"label": "Structure/Defects", "role": "yellow"},
        {"label": "Processing Route", "role": "yellow"},
        {"label": "Synthesize/Process", "role": "green"},
        {"label": "Measure Properties", "role": "green"},
        {"label": "Structure–Property Insight", "role": "violet"},
    ],
    "medicinal_chemistry": [
        {"label": "Biological Target", "role": "red"},
        {"label": "Lead Compound", "role": "red"},
        {"label": "SAR Hypotheses", "role": "yellow"},
        {"label": "Design & Synthesize Analogues", "role": "green"},
        {"label": "ADME/Tox Screening", "role": "green"},
        {"label": "Optimize Potency/Selectivity", "role": "blue"},
        {"label": "Candidate Molecule", "role": "violet"},
    ],
    "nuclear_chemistry": [
        {"label": "Radionuclide/System", "role": "red"},
        {"label": "Radiation Type + Energy", "role": "red"},
        {"label": "Containment/Safety Controls", "role": "yellow"},
        {"label": "Separation/Processing", "role": "green"},
        {"label": "Detection/Counting", "role": "green"},
        {"label": "Decay/Transport Analysis", "role": "blue"},
        {"label": "Nuclear Chemistry Result", "role": "violet"},
    ],
    "organic_chemistry": [
        {"label": "Starting Materials", "role": "red"},
        {"label": "Reagents/Catalyst", "role": "red"},
        {"label": "Solvent/Conditions", "role": "yellow"},
        {"label": "Reaction Mechanism Steps", "role": "yellow"},
        {"label": "Run Reaction", "role": "green"},
        {"label": "Workup/Purification", "role": "green"},
        {"label": "Structure Confirmation", "role": "blue"},
        {"label": "Organic Product", "role": "violet"},
    ],
    "physical_chemistry": [
        {"label": "System Definition", "role": "red"},
        {"label": "State Variables (T,P,composition)", "role": "red"},
        {"label": "Model/Framework", "role": "yellow"},
        {"label": "Acquire Measurements", "role": "green"},
        {"label": "Fit Parameters/Equilibria", "role": "green"},
        {"label": "Thermo/Kinetic Interpretation", "role": "blue"},
        {"label": "Physical Chemistry Result", "role": "violet"},
    ],
    "polymer_chemistry": [
        {"label": "Monomers + Additives", "role": "red"},
        {"label": "Initiator/Catalyst", "role": "red"},
        {"label": "Polymerization Conditions", "role": "yellow"},
        {"label": "Initiation/Propagation/Termination", "role": "yellow"},
        {"label": "Run Polymerization", "role": "green"},
        {"label": "Molecular Weight/Structure Analysis", "role": "blue"},
        {"label": "Polymer Material", "role": "violet"},
    ],
    "quantum_chemistry": [
        {"label": "Molecular Hamiltonian Setup", "role": "red"},
        {"label": "Basis Set/Representation", "role": "yellow"},
        {"label": "Electronic Structure Method", "role": "yellow"},
        {"label": "Solve Schrödinger Equation (approx.)", "role": "green"},
        {"label": "Wavefunction/Density", "role": "blue"},
        {"label": "Energies/Orbitals/Properties", "role": "violet"},
    ],
    "spectroscopy_advanced": [
        {"label": "Sample", "role": "red"},
        {"label": "Instrument Configuration", "role": "yellow"},
        {"label": "Acquire Spectrum/Pattern", "role": "green"},
        {"label": "Preprocess (baseline/noise)", "role": "green"},
        {"label": "Peak/Feature Extraction", "role": "blue"},
        {"label": "Assign/Interpret", "role": "green"},
        {"label": "Spectroscopic Conclusion", "role": "violet"},
    ],
    "surface_chemistry": [
        {"label": "Surface/Interface System", "role": "red"},
        {"label": "Adsorbates/Reactants", "role": "red"},
        {"label": "Surface Sites + Morphology", "role": "yellow"},
        {"label": "Adsorption/Reaction Step", "role": "green"},
        {"label": "Measure Surface Response", "role": "green"},
        {"label": "Isotherm/Kinetics Interpretation", "role": "blue"},
        {"label": "Surface Chemistry Result", "role": "violet"},
    ],
    "theoretical_chemistry": [
        {"label": "Chemical Problem Definition", "role": "red"},
        {"label": "Assumptions/Approximations", "role": "yellow"},
        {"label": "Mathematical Model", "role": "yellow"},
        {"label": "Derive Equations/Predictions", "role": "green"},
        {"label": "Compare to Data/Trends", "role": "blue"},
        {"label": "Theoretical Insight", "role": "violet"},
    ],
    "thermodynamics": [
        {"label": "System + Process Path", "role": "red"},
        {"label": "State Variables (T,P,n)", "role": "red"},
        {"label": "Thermo Data (ΔH, ΔS, Cp)", "role": "yellow"},
        {"label": "Compute ΔG / Equilibrium", "role": "green"},
        {"label": "Phase/Reaction Feasibility", "role": "blue"},
        {"label": "Thermodynamic Result", "role": "violet"},
    ],
}


# Biology subcategory templates (for applying non-generic Mermaid while preserving citations).
BIOLOGY_SUBCATEGORY_TEMPLATES: Dict[str, List[Step]] = {
    "coordination_control": [
        {"label": "Stimulus / Internal Signal", "role": "red"},
        {"label": "Sensors / Receptors", "role": "yellow"},
        {"label": "Signal Transduction", "role": "green"},
        {"label": "Integration Center (neural/endocrine)", "role": "blue"},
        {"label": "Effector Activation", "role": "green"},
        {"label": "Physiological Response", "role": "violet"},
    ],
    "nutrition_metabolism": [
        {"label": "Nutrient/Energy Input", "role": "red"},
        {"label": "Acquisition/Intake", "role": "green"},
        {"label": "Transport to Cells", "role": "blue"},
        {"label": "Catabolism/Anabolism", "role": "green"},
        {"label": "Energy Storage/Use", "role": "blue"},
        {"label": "Growth/Work Output", "role": "violet"},
    ],
    "sensory_perception": [
        {"label": "External Stimulus", "role": "red"},
        {"label": "Sensory Organ/Cells", "role": "yellow"},
        {"label": "Transduction to Neural Signal", "role": "green"},
        {"label": "Neural Pathways", "role": "blue"},
        {"label": "Perception/Interpretation", "role": "green"},
        {"label": "Behavioral/Physiological Output", "role": "violet"},
    ],
    "transport_circulation": [
        {"label": "Substance to Transport", "role": "red"},
        {"label": "Transport Medium (blood/xylem/etc.)", "role": "yellow"},
        {"label": "Pumping/Driving Force", "role": "green"},
        {"label": "Distribution Network", "role": "yellow"},
        {"label": "Exchange at Target Tissues", "role": "green"},
        {"label": "Delivered/Removed Substances", "role": "violet"},
    ],
    "behavior_communication": [
        {"label": "Context / Trigger", "role": "red"},
        {"label": "Sensory Inputs", "role": "yellow"},
        {"label": "Decision/Planning", "role": "blue"},
        {"label": "Motor Output/Action", "role": "green"},
        {"label": "Social/Environmental Feedback", "role": "blue"},
        {"label": "Behavioral Outcome", "role": "violet"},
    ],
    "reproduction_development": [
        {"label": "Reproductive/Developmental Cue", "role": "red"},
        {"label": "Gametogenesis/Preparation", "role": "green"},
        {"label": "Fertilization/Initiation", "role": "green"},
        {"label": "Growth & Patterning", "role": "blue"},
        {"label": "Differentiation/Organogenesis", "role": "green"},
        {"label": "Mature Offspring/Structure", "role": "violet"},
    ],
    "defense_immune": [
        {"label": "Threat/Pathogen Exposure", "role": "red"},
        {"label": "Recognition (innate sensors)", "role": "yellow"},
        {"label": "Signal Amplification", "role": "green"},
        {"label": "Effector Response", "role": "green"},
        {"label": "Resolution/Memory (if any)", "role": "blue"},
        {"label": "Protection/Recovery", "role": "violet"},
    ],
    "growth_morphogenesis": [
        {"label": "Growth Signal", "role": "red"},
        {"label": "Stem/Progenitor Cells", "role": "yellow"},
        {"label": "Proliferation", "role": "green"},
        {"label": "Differentiation", "role": "blue"},
        {"label": "Morphogenesis/Remodeling", "role": "green"},
        {"label": "Formed Tissue/Structure", "role": "violet"},
    ],
}

