graph TD
    FF[Strong transcription] --> II[lacZ mRNA]
    FF --> JJ[lacY mRNA]
    FF --> KK[lacA mRNA]
    II --> OO[Beta-galactosidase]
    JJ --> PP[LacY permease]
    KK --> QQ[LacA]
    OO --> RR[Lactose hydrolysis]
    style FF fill:#94a3b8,color:#fff
    style II fill:#51cf66,color:#fff
    style JJ fill:#51cf66,color:#fff
    style KK fill:#51cf66,color:#fff
    style OO fill:#51cf66,color:#fff
    style PP fill:#94a3b8,color:#fff
    style QQ fill:#94a3b8,color:#fff
    style RR fill:#7950f2,color:#fff
