#!/usr/bin/env bash
# Safe local cleanup after Zenodo v6 + GitHub push (June 2026).
# Deletes regenerable build junk; archives personal/draft files.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PAPERS="$ROOT/papers"
ARCHIVE="$PAPERS/_local_archive"
mkdir -p "$ARCHIVE"/{pdf,drafts,job_applications,docx}

echo "=== Copernicus local cleanup ==="

# --- Delete: PDF/Mermaid build intermediates (regenerated by build_revised_pdf.py) ---
cd "$PAPERS"
rm -fv fig_*_[0-9]*.png fig_*_[0-9]*.mmd 2>/dev/null || true
rm -fv pdf_header_[0-9]*.tex puppeteer-config-pdf_[0-9]*.json puppeteer-config_[0-9]*.json 2>/dev/null || true
rm -fv knowledge_engine_vision_revised_pdfbuild_[0-9]*.md knowledge_engine_vision_revised_build_[0-9]*.md 2>/dev/null || true
rm -fv fig_query_lifecycle_[0-9]*.mmd fig_capability_loop_[0-9]*.mmd 2>/dev/null || true
rm -fv fig_cap_p.mmd fig_life_p.mmd knowledge_engine_vision_revised_pdfbuild.md knowledge_engine_vision_revised_build.md 2>/dev/null || true
mkdir -p "$ARCHIVE/figures"
mv -fv fig_*.png fig_*.mmd figure2_* figure4_* "$ARCHIVE/figures/" 2>/dev/null || true
rm -fv pdf_header.tex puppeteer-config-pdf.json puppeteer-config.json 2>/dev/null || true
rm -rfv .cache 2>/dev/null || true
rm -fv ~$*.docx 2>/dev/null || true

# Windows WSL metadata
find "$ROOT" -name '*:Zone.Identifier' -delete 2>/dev/null || true

# --- Archive: duplicate/old PDFs (keep canonical __FINAL locally) ---
for f in \
  knowledge_engine_vision.pdf \
  knowledge_engine_vision_revised_FINAL.pdf \
  knowledge_engine_vision_revised_SUBMIT.pdf
do
  [[ -f "$PAPERS/$f" ]] && mv -v "$PAPERS/$f" "$ARCHIVE/pdf/"
done

# --- Archive: job application materials ---
for f in \
  Gary_Welz_Biohub_Research_Scientist_AI_CV.md \
  Gary_Welz_Biohub_Research_Scientist_AI_CV.html \
  Gary_Welz_Biohub_Research_Scientist_AI_CV.pdf \
  Gary_Welz_Biohub_Research_Scientist_AI_Cover_Letter.md \
  Gary_Welz_Biohub_Research_Scientist_AI_Cover_Letter.pdf \
  BIOHUB_RESEARCH_SCIENTIST_AI_APPLICATION_DRAFT.md
do
  [[ -f "$PAPERS/$f" ]] && mv -v "$PAPERS/$f" "$ARCHIVE/job_applications/"
done

# --- Archive: unrelated HTML paper drafts ---
for f in \
  genome_as_computer_v2.html \
  GLMP_Foundational_Typology.html \
  GLMP_Genomic_Complexity_Synthesis_bioRxiv.html \
  empirical_sequel_draft.html
do
  [[ -f "$PAPERS/$f" ]] && mv -v "$PAPERS/$f" "$ARCHIVE/drafts/"
done

# --- Archive: redundant docx exports ---
for f in \
  knowledge_engine_vision_pandoc.docx \
  knowledge_engine_vision_revised.docx \
  Cover_Letter_Discover_AI.docx
do
  [[ -f "$PAPERS/$f" ]] && mv -v "$PAPERS/$f" "$ARCHIVE/docx/"
done

# --- Root: stray duplicate script ---
[[ -f "$ROOT/backfill_embeddings.py" ]] && mv -v "$ROOT/backfill_embeddings.py" "$ARCHIVE/drafts/backfill_embeddings.py.root_copy"

# --- Root: one-off planning notes → archive ---
mkdir -p "$ROOT/local_archive/notes"
for f in \
  GCS_CLEANUP_PLAN.md \
  FIREBASE_STUDIO_PRE_TRIP_CHECKLIST.md \
  FIREBASE_STUDIO_MIGRATION_NOTE.md
do
  [[ -f "$ROOT/$f" ]] && mv -v "$ROOT/$f" "$ROOT/local_archive/notes/"
done

echo ""
echo "Kept locally (gitignored, on Zenodo):"
ls -lh "$PAPERS"/openai_doc_embeddings.npz "$PAPERS"/dense_track_a_bundle_20260608.zip "$PAPERS"/research_papers_20260526.jsonl.gz 2>/dev/null || true
echo "Canonical PDF: $PAPERS/knowledge_engine_vision_revised__FINAL.pdf"
echo "Archive: $ARCHIVE and $ROOT/local_archive/"
echo "Done."
